const STORAGE_KEY='fleek_impact_connect_v1';
const $=id=>document.getElementById(id);
const els={purchaseBtn:$('purchaseBtn'),newOrderBtn:$('newOrderBtn'),status:$('status'),buyerMetrics:$('buyerMetrics'),sellerMetrics:$('sellerMetrics'),buyerChart:$('buyerChart'),sellerChart:$('sellerChart'),buyerTable:$('buyerTable'),sellerTable:$('sellerTable'),buyerAdvice:$('buyerAdvice'),buyerAdviceText:$('buyerAdviceText'),sellerAdvice:$('sellerAdvice'),sellerAdviceText:$('sellerAdviceText'),commercialMetrics:$('commercialMetrics'),passportRows:$('passportRows'),receiptModal:$('receiptModal'),receiptTitle:$('receiptTitle'),receiptMeta:$('receiptMeta'),receiptGrid:$('receiptGrid'),consentModal:$('consentModal'),consentRows:$('consentRows'),consentCheck:$('consentCheck'),connectBtn:$('connectBtn'),continueBtn:$('continueBtn'),offerModal:$('offerModal'),realPartnerBtn:$('realPartnerBtn')};

function enrich(order){const f=IMPACT_FACTORS[order.category];return{...order,receiptId:`IMP-${order.id}`,categoryLabel:f.label,co2:Math.round(order.weight*f.co2),water:Math.round(order.items*f.water),cost:order.value/order.items};}
function seeded(){return SEED_ORDERS.map(enrich);}
function getOrders(){try{const value=localStorage.getItem(STORAGE_KEY);if(!value){const initial=seeded();setOrders(initial);return initial;}return JSON.parse(value);}catch{return seeded();}}
function setOrders(orders){localStorage.setItem(STORAGE_KEY,JSON.stringify(orders));}
function buyerOrders(){return getOrders().filter(o=>o.buyer==='Second Story Vintage').sort((a,b)=>new Date(b.date)-new Date(a.date));}
function sellerOrders(){return getOrders().filter(o=>o.seller==='North Star Wholesale').sort((a,b)=>new Date(b.date)-new Date(a.date));}
function totals(orders){return orders.reduce((a,o)=>({orders:a.orders+1,items:a.items+o.items,weight:a.weight+o.weight,co2:a.co2+o.co2,water:a.water+o.water,value:a.value+o.value}),{orders:0,items:0,weight:0,co2:0,water:0,value:0});}
function fmt(n){return new Intl.NumberFormat('en-GB').format(n);}
function money(n){return new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n);}
function metricHTML(t){return `<div class="metric"><small>TOTAL ORDERS</small><strong>${t.orders}</strong></div><div class="metric"><small>GARMENTS</small><strong>${fmt(t.items)}</strong></div><div class="metric"><small>TEXTILES KEPT IN USE</small><strong>${fmt(t.weight)} kg</strong></div><div class="metric"><small>EST. CO₂e AVOIDED</small><strong>${(t.co2/1000).toFixed(2)} t</strong></div><div class="metric"><small>EST. WATER SAVED</small><strong>${fmt(t.water)} L</strong></div><div class="metric"><small>ORDER VALUE</small><strong>${money(t.value)}</strong></div><div class="metric"><small>AVG ITEMS / ORDER</small><strong>${t.orders?Math.round(t.items/t.orders):0}</strong></div><div class="metric"><small>IMPACT RECORDS</small><strong>${t.orders}</strong></div>`;}
function chartHTML(orders,key){const d=[...orders].reverse(),max=Math.max(...d.map(o=>o[key]),1);return d.map(o=>`<div class="bar-wrap"><div class="bar" style="height:${Math.max(8,o[key]/max*140)}px" title="${o[key]}"></div><div class="bar-label">${o.id.slice(-4)}</div></div>`).join('');}
function tableHTML(orders,role){return `<table><thead><tr><th>ORDER</th><th>DATE</th><th>${role==='buyer'?'SELLER':'BUYER'}</th><th>GARMENTS</th><th>CO₂e</th><th></th></tr></thead><tbody>${orders.map((o,i)=>`<tr><td><b>${o.id}</b></td><td>${new Date(o.date).toLocaleDateString('en-GB')}</td><td>${role==='buyer'?o.seller:o.buyer}</td><td>${o.items}</td><td>${o.co2} kg</td><td><button class="text-btn" onclick="showReceipt('${role}',${i})">View</button></td></tr>`).join('')}</tbody></table>`;}
function advice(t,role){const qualified=t.co2>=COMMERCIAL_ASSUMPTIONS.activationThresholdKg;const subject=role==='buyer'?'purchasing':'sales';return{title:qualified?'Carbonfuture is your strongest next-step partner.':'Keep building your verified impact history.',text:qualified?`Across ${t.orders} orders, your ${subject} activity represents an estimated ${(t.co2/1000).toFixed(2)} tonnes of avoided CO₂e. Fleek can package this history into an Impact Passport, reducing manual onboarding for a climate partner.`:`You are ${fmt(COMMERCIAL_ASSUMPTIONS.activationThresholdKg-t.co2)} kg away from the prototype activation threshold.`};}
function passportHTML(t){return `<div class="passport-row"><span>Business</span><b>Second Story Vintage</b></div><div class="passport-row"><span>Verified Fleek orders</span><b>${t.orders}</b></div><div class="passport-row"><span>Garments recirculated</span><b>${fmt(t.items)}</b></div><div class="passport-row"><span>Textiles kept in use</span><b>${fmt(t.weight)} kg</b></div><div class="passport-row"><span>Estimated CO₂e avoided</span><b>${(t.co2/1000).toFixed(2)} t</b></div><div class="passport-row"><span>Verification source</span><b>Fleek order records</b></div>`;}
function commercialHTML(t){const qualified=t.co2>=COMMERCIAL_ASSUMPTIONS.activationThresholdKg;return `<div class="commercial"><small>PROTOTYPE STATUS</small><strong>${qualified?'Qualified':'Building history'}</strong></div><div class="commercial"><small>EST. CUSTOMER VALUE</small><strong>£${COMMERCIAL_ASSUMPTIONS.annualCustomerValue}/yr</strong></div><div class="commercial"><small>EST. FLEEK ENABLEMENT REVENUE</small><strong>£${COMMERCIAL_ASSUMPTIONS.enablementRevenue}</strong></div>`;}
function render(){const bo=buyerOrders(),so=sellerOrders(),bt=totals(bo),st=totals(so);els.buyerMetrics.innerHTML=metricHTML(bt);els.sellerMetrics.innerHTML=metricHTML(st);els.buyerChart.innerHTML=chartHTML(bo,'co2');els.sellerChart.innerHTML=chartHTML(so,'items');els.buyerTable.innerHTML=tableHTML(bo,'buyer');els.sellerTable.innerHTML=tableHTML(so,'seller');const ba=advice(bt,'buyer'),sa=advice(st,'seller');els.buyerAdvice.textContent=ba.title;els.buyerAdviceText.textContent=ba.text;els.sellerAdvice.textContent=sa.title;els.sellerAdviceText.textContent=sa.text;els.commercialMetrics.innerHTML=commercialHTML(bt);els.passportRows.innerHTML=passportHTML(bt);els.consentRows.innerHTML=passportHTML(bt);}
function completePurchase(){const all=getOrders();const seq=3000+all.length+1;const order=enrich({...DEMO_ORDER,id:`FLK-2026-${seq}`,date:new Date().toISOString()});all.push(order);setOrders(all);els.purchaseBtn.classList.add('hidden');els.newOrderBtn.classList.remove('hidden');els.status.classList.remove('hidden');render();openReceipt(order);}
function openReceipt(o){els.receiptTitle.textContent=`${o.buyer} × ${o.seller}`;els.receiptMeta.textContent=`${o.receiptId} · Order ${o.id}`;els.receiptGrid.innerHTML=`<div class="receipt-cell"><small>GARMENTS</small><strong>${o.items}</strong></div><div class="receipt-cell"><small>TEXTILES KEPT IN USE</small><strong>${o.weight} kg</strong></div><div class="receipt-cell"><small>EST. CO₂e AVOIDED</small><strong>${o.co2} kg</strong></div><div class="receipt-cell"><small>EST. WATER SAVED</small><strong>${fmt(o.water)} L</strong></div><div class="receipt-cell"><small>AVERAGE COST / ITEM</small><strong>£${o.cost.toFixed(2)}</strong></div><div class="receipt-cell"><small>BUNDLE TYPE</small><strong>${o.categoryLabel}</strong></div>`;els.receiptModal.classList.add('show');}
function showReceipt(role,index){const o=(role==='buyer'?buyerOrders():sellerOrders())[index];if(o)openReceipt(o);}window.showReceipt=showReceipt;
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});}
function resetDemo(){if(confirm('Restore the five historical buyer orders and five historical seller orders?')){localStorage.removeItem(STORAGE_KEY);els.purchaseBtn.classList.remove('hidden');els.newOrderBtn.classList.add('hidden');els.status.classList.add('hidden');render();showView('checkout');}}

document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
document.querySelectorAll('[data-open-connect]').forEach(b=>b.addEventListener('click',()=>showView('connect')));
document.querySelectorAll('[data-reset]').forEach(b=>b.addEventListener('click',resetDemo));
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).classList.remove('show')));
document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.remove('show')}));
els.purchaseBtn.addEventListener('click',completePurchase);
els.newOrderBtn.addEventListener('click',()=>{els.purchaseBtn.classList.remove('hidden');els.newOrderBtn.classList.add('hidden');els.status.classList.add('hidden')});
els.connectBtn.addEventListener('click',()=>{render();els.consentCheck.checked=false;els.consentModal.classList.add('show')});
els.continueBtn.addEventListener('click',()=>{if(!els.consentCheck.checked){alert('Please confirm consent before continuing.');return;}els.consentModal.classList.remove('show');els.offerModal.classList.add('show');});
els.realPartnerBtn.addEventListener('click',()=>window.open('https://www.carbonfuture.com/buyers','_blank','noopener,noreferrer'));
render();